import type { Language } from './contracts.js';
export const BRAND_NAME = "garlicvread's";
export const LOCALES: Readonly<Record<Language, string>> = { ko: 'ko-KR', en: 'en-GB', de: 'de-DE' };
export const COPY = {
  en: {
    brandSubtitle: 'Mensa Menu Translator',
    skip: 'Skip to menus', language: 'Language', title: 'Mensa menu', view: 'Menu view', dayView: 'By day', weekView: 'The whole week', navigation: 'Menu dates', previousWeek: 'Previous available week', nextWeek: 'Next available week', today: 'Today', chooseDate: 'Choose a date', allDates: 'All published dates', priceGroup: 'Prices for', student: 'Students', staff: 'Staff', guest: 'Guests', loading: 'Getting the menu ready…', source: 'Original menu ↗', thisWeek: 'This week', nextWeekLabel: 'Next week', publishedWeek: 'Published week', weekTitle: 'Weekly menu', todayMenu: 'On the menu today', pastMenu: 'Past menu', componentDetails: 'Component details', notices: 'Ingredients · allergens · additives', original: 'German original', fallback: 'Original German · translation unavailable', checkPrice: 'Price not listed when collected ↗', checkPriceAria: 'Price was not listed when collected; open the original menu', vegan: 'Vegan', vegetarian: 'Vegetarian', empty: 'No meals are published for this date.', pastNotice: 'You are viewing a past menu. It is not today’s offering.', expiredNotice: 'All available menus are in the past. Check the original menu for current information.', staleNotice: 'This snapshot is more than two days old. Check the original menu for updates.', translationsFailed: 'Translations could not be loaded. The German menu is still available.', errorTitle: 'Menu unavailable', errorBody: 'We couldn’t load a valid menu right now. Try again, or visit the original menu.', retry: 'Try again', openDay: 'View day', todayUnavailable: 'Today is not published; showing the next available menu.', latestPast: 'Showing the latest available past menu.'
  },
  ko: {
    brandSubtitle: '멘자 식단 번역기',
    skip: '메뉴로 바로 이동', language: '언어', title: '멘자 식단', view: '메뉴 보기 방식', dayView: '하루씩 보기', weekView: '한 주 보기', navigation: '메뉴 날짜', previousWeek: '이전 식단 주간', nextWeek: '다음 식단 주간', today: '오늘', chooseDate: '날짜 선택', allDates: '공개된 모든 날짜', priceGroup: '가격 기준', student: '학생', staff: '교직원', guest: '방문객', loading: '메뉴를 불러오는 중…', source: '원본 식단표 ↗', thisWeek: '이번 주', nextWeekLabel: '다음 주', publishedWeek: '공개된 주간 식단', weekTitle: '주간 식단', todayMenu: '오늘의 점심', pastMenu: '지난 식단', componentDetails: '구성품별 정보', notices: '식재료 · 알레르기 · 첨가물', original: '독일어 원문', fallback: '독일어 원문 · 번역 준비 중', checkPrice: '수집 당시 가격 미기재 ↗', checkPriceAria: '수집 당시 가격이 미기재되어 원본 식단표를 엽니다', vegan: '비건', vegetarian: '채식', empty: '이 날짜에 공개된 메뉴가 없습니다.', pastNotice: '지난 날짜의 식단이며 오늘 제공되는 메뉴가 아닙니다.', expiredNotice: '공개된 메뉴가 모두 지난 날짜의 식단입니다. 최신 메뉴는 원본 식단표에서 확인해 주세요.', staleNotice: '마지막 수집 후 이틀 이상 경과했습니다. 원본 식단표에서 최신 정보를 확인해 주세요.', translationsFailed: '번역을 불러오지 못해 독일어 원문으로 표시합니다.', errorTitle: '메뉴를 잠시 불러올 수 없습니다', errorBody: '유효한 식단을 불러오지 못했습니다. 다시 시도하거나 원본 식단표에서 확인해 주세요.', retry: '다시 시도', openDay: '하루 보기', todayUnavailable: '오늘 식단이 없어 다음 공개 날짜로 이동합니다.', latestPast: '가장 최근에 공개된 지난 식단으로 이동합니다.'
  },
  de: {
    brandSubtitle: 'Mensa-Menüübersetzer',
    skip: 'Zum Speiseplan', language: 'Sprache', title: 'Speiseplan', view: 'Ansicht', dayView: 'Tagesansicht', weekView: 'Wochenansicht', navigation: 'Menüdaten', previousWeek: 'Vorherige verfügbare Woche', nextWeek: 'Nächste verfügbare Woche', today: 'Heute', chooseDate: 'Datum wählen', allDates: 'Alle veröffentlichten Tage', priceGroup: 'Preise für', student: 'Studierende', staff: 'Bedienstete', guest: 'Gäste', loading: 'Der Speiseplan wird geladen…', source: 'Original-Speiseplan ↗', thisWeek: 'Diese Woche', nextWeekLabel: 'Nächste Woche', publishedWeek: 'Veröffentlichte Woche', weekTitle: 'Wochenplan', todayMenu: 'Heute auf dem Speiseplan', pastMenu: 'Vergangener Speiseplan', componentDetails: 'Bestandteile', notices: 'Zutaten · Allergene · Zusatzstoffe', original: 'Deutsches Original', fallback: 'Deutsches Original · Übersetzung nicht verfügbar', checkPrice: 'Bei Abruf ohne Preis ↗', checkPriceAria: 'Beim Abruf war kein Preis angegeben; Original-Speiseplan öffnen', vegan: 'Vegan', vegetarian: 'Vegetarisch', empty: 'Für diesen Tag sind keine Gerichte veröffentlicht.', pastNotice: 'Dieser Speiseplan liegt in der Vergangenheit und gilt nicht für heute.', expiredNotice: 'Alle verfügbaren Speisepläne liegen in der Vergangenheit. Aktuelle Angaben stehen im Original-Speiseplan.', staleNotice: 'Dieser Stand ist über zwei Tage alt. Bitte den Original-Speiseplan prüfen.', translationsFailed: 'Übersetzungen konnten nicht geladen werden. Das deutsche Original ist weiterhin verfügbar.', errorTitle: 'Speiseplan nicht verfügbar', errorBody: 'Der Speiseplan konnte gerade nicht geladen werden. Bitte erneut versuchen oder den Original-Speiseplan öffnen.', retry: 'Erneut versuchen', openDay: 'Tag ansehen', todayUnavailable: 'Heute ist kein Menü veröffentlicht; der nächste verfügbare Tag wird angezeigt.', latestPast: 'Der zuletzt veröffentlichte vergangene Speiseplan wird angezeigt.'
  }
} as const;
export type CopyKey = keyof typeof COPY.en;
export type Copy = Readonly<Record<CopyKey, string>>;
export function copyFor(language: Language): Copy { return COPY[language]; }
export function isCopyKey(value: unknown): value is CopyKey { return typeof value === 'string' && Object.hasOwn(COPY.en, value); }
